--[[
    This user patch is primarily for use with the Project: Title plugin. It requires
    Project: Title v3.6 or higher.

    It allows forcing a specific aspect ratio for cover art in grid mode. Setting
    stretch_covers to true and stretch_ratio to 1 results in the cover using the maximum
    amount of horizontal and vertical space.

    Folder covers are not affected. Autogenerated folder cover thumbnails are not affected.
    Fake covers created for books without cover art are not affected. The iconography based
    covers used for documents like .txt and unsupported files are not affected.

    Setting stretch_ratio above 1 results in covers overlapping. Not recommended.

    Setting stretch_ratio between 0 and 1 results in the stretched covers using
    proportionally less horizontal space than vertical space. ie: they beoome narrower.

    Important detail: The available space is almost never a perfect square. The available height
    and width change based on how many items per row and column you have chosen for your grid.
    This means that a ratio of 1 does not result in perfectly square covers. It results in covers
    that use ALL the space, which might be wider than it is taller, or vice versa.
    
    You will need to experiment with the value of stretch_ratio to find what you like best. In 
    testing this on my device, 0.8 produced uniform "book-like" covers on a 3x3 grid.
--]]

local userpatch = require("userpatch")
local function patchCoverBrowser(plugin)
    local ptutil = require("ptutil")
    ptutil.grid_defaults.stretch_covers = true
    ptutil.grid_defaults.stretch_ratio = 0.85
end
userpatch.registerPatchPluginFunc("coverbrowser", patchCoverBrowser)